services:
  schema-evolution-framework-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: SchemaEvolutionFramework
    env_file:
      - ./.env
    networks:
      - data-automation-net
    volumes:
      - ./:/app
      - ${HOST_DATA_DIRECTORY}:${CONTAINER_DATA_DIR}
      - /var/run/docker.sock:/var/run/docker.sock
      - delta-jars:/opt/delta-jars:ro
      - ext-jars:/opt/ext-jars:ro
      - jdbc-driver:/opt/jdbc-jars:ro
      - ./hive-site.xml:/opt/spark/conf/hive-site.xml:ro
    ports:
      - "4043:4043"
    depends_on:
      sef-spark-master:
        condition: service_healthy
      sef-spark-worker-1:
        condition: service_healthy
      sef-spark-worker-2:
        condition: service_healthy
    restart: unless-stopped
    stop_grace_period: 90s

  sef-spark-master:
    user: "0:0"
    image: apache/spark:3.5.6
    container_name: sef-spark-master
    environment:
      - SPARK_MASTER_PORT=7079
      - SPARK_MASTER_WEBUI_PORT=8070
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - SPARK_CLASSPATH=/opt/delta-jars/*:/opt/ext-jars/*
      - UMASK=0002
      - SPARK_MASTER_OPTS=-Dspark.hadoop.fs.permissions.umask-mode=002
      - SPARK_NO_DAEMONIZE=1
      - SPARK_LOG_DIR=/tmp/spark/logs
      - SPARK_PID_DIR=/tmp/spark/pids
    command:
      - /bin/bash
      - -lc
      - >
        set -Eeuo pipefail;
        /opt/spark/sbin/start-master.sh
        -h sef-spark-master
        -p "${SPARK_MASTER_PORT:-7079}"
        --webui-port "${SPARK_MASTER_WEBUI_PORT:-8070}";
        tail -F /opt/spark/logs/* &
        wait -n
    volumes:
      - ${HOST_DATA_DIRECTORY}:${CONTAINER_DATA_DIR}
      - ${HOST_SPARK_WAREHOUSE_DIR}:${CONTAINER_WAREHOUSE_DIR}
      - ./hive-site.xml:/opt/spark/conf/hive-site.xml:ro
      - delta-jars:/opt/delta-jars:ro
      - ext-jars:/opt/ext-jars:ro
    ports:
      - "7079:7079"
      - "8070:8070"
    networks: [ data-automation-net ]
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "bash -lc 'exec 3<>/dev/tcp/127.0.0.1/8070 && exec 3>&- 3<&- || exit 1'" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s

  sef-spark-worker-1:
    user: "0:0"
    image: apache/spark:3.5.6
    container_name: sef-spark-worker-1
    depends_on:
      sef-spark-master:
        condition: service_healthy
    environment:
      - SPARK_WORKER_MEMORY=4g
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_WEBUI_PORT=8091
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - SPARK_CLASSPATH=/opt/delta-jars/*:/opt/ext-jars/*
      - UMASK=0002
      - SPARK_WORKER_OPTS=-Dspark.hadoop.fs.permissions.umask-mode=002
      - SPARK_NO_DAEMONIZE=1
      - SPARK_LOG_DIR=/tmp/spark/logs
      - SPARK_PID_DIR=/tmp/spark/pids
    # platform: linux/amd64
    command:
      - /bin/bash
      - -lc
      - >
        set -Eeuo pipefail;
        /opt/spark/sbin/start-worker.sh
        --webui-port "${SPARK_WORKER_WEBUI_PORT:-8071}"
        -c "${SPARK_WORKER_CORES:-4}"
        -m "${SPARK_WORKER_MEMORY:-4g}"
        spark://sef-spark-master:7079;
        tail -F /opt/spark/logs/* &
        wait -n
    volumes:
      - ${HOST_DATA_DIRECTORY}:${CONTAINER_DATA_DIR}
      - ${HOST_SPARK_WAREHOUSE_DIR}:${CONTAINER_WAREHOUSE_DIR}
      - ./hive-site.xml:/opt/spark/conf/hive-site.xml:ro
      - delta-jars:/opt/delta-jars:ro
      - ext-jars:/opt/ext-jars:ro
    ports: [ "8071:8071" ]
    networks: [ data-automation-net ]
    healthcheck:
      test: [ "CMD-SHELL", "bash -lc 'exec 3<>/dev/tcp/127.0.0.1/8071 && exec 3>&- 3<&- || exit 1'" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s

  sef-spark-worker-2:
    user: "0:0"
    image: apache/spark:3.5.6
    container_name: sef-spark-worker-2
    depends_on:
      sef-spark-master:
        condition: service_healthy
    environment:
      - SPARK_WORKER_MEMORY=4g
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_WEBUI_PORT=8092
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - SPARK_CLASSPATH=/opt/delta-jars/*:/opt/ext-jars/*
      - UMASK=0002
      - SPARK_WORKER_OPTS=-Dspark.hadoop.fs.permissions.umask-mode=002
      - SPARK_NO_DAEMONIZE=1
      - SPARK_LOG_DIR=/tmp/spark/logs
      - SPARK_PID_DIR=/tmp/spark/pids
    # platform: linux/amd64
    command:
      - /bin/bash
      - -lc
      - >
        set -Eeuo pipefail;
        /opt/spark/sbin/start-worker.sh
        --webui-port "${SPARK_WORKER_WEBUI_PORT:-8072}"
        -c "${SPARK_WORKER_CORES:-4}"
        -m "${SPARK_WORKER_MEMORY:-4g}"
        spark://sef-spark-master:7079;
        tail -F /opt/spark/logs/* &
        wait -n
    volumes:
      - ${HOST_DATA_DIRECTORY}:${CONTAINER_DATA_DIR}
      - ${HOST_SPARK_WAREHOUSE_DIR}:${CONTAINER_WAREHOUSE_DIR}
      - ./hive-site.xml:/opt/spark/conf/hive-site.xml:ro
      - delta-jars:/opt/delta-jars:ro
      - ext-jars:/opt/ext-jars:ro
    ports: [ "8072:8072" ]
    networks: [ data-automation-net ]
    healthcheck:
      test: [ "CMD-SHELL", "bash -lc 'exec 3<>/dev/tcp/127.0.0.1/8072 && exec 3>&- 3<&- || exit 1'" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 5s

volumes:
  ext-jars:
    external: true
  jdbc-driver:
    external: true
  delta-jars:
    external: true


networks:
  data-automation-net:
    external: true