# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import sef_handlers_pb2 as sef__handlers__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sef_handlers_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LakeHandlerStub(object):
    """Lake handler gRPC API

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ApplyOperations = channel.unary_unary(
            '/sef.handlers.v1.LakeHandler/ApplyOperations',
            request_serializer=sef__handlers__pb2.OperationBatch.SerializeToString,
            response_deserializer=sef__handlers__pb2.OperationBatchResult.FromString,
            _registered_method=True)
        self.IntrospectEvidence = channel.unary_unary(
            '/sef.handlers.v1.LakeHandler/IntrospectEvidence',
            request_serializer=sef__handlers__pb2.EvidenceRequest.SerializeToString,
            response_deserializer=sef__handlers__pb2.EvidenceResponse.FromString,
            _registered_method=True)


class LakeHandlerServicer(object):
    """Lake handler gRPC API

    """

    def ApplyOperations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IntrospectEvidence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LakeHandlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'ApplyOperations': grpc.unary_unary_rpc_method_handler(
            servicer.ApplyOperations,
            request_deserializer=sef__handlers__pb2.OperationBatch.FromString,
            response_serializer=sef__handlers__pb2.OperationBatchResult.SerializeToString,
        ),
        'IntrospectEvidence': grpc.unary_unary_rpc_method_handler(
            servicer.IntrospectEvidence,
            request_deserializer=sef__handlers__pb2.EvidenceRequest.FromString,
            response_serializer=sef__handlers__pb2.EvidenceResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'sef.handlers.v1.LakeHandler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sef.handlers.v1.LakeHandler', rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class LakeHandler(object):
    """Lake handler gRPC API

    """

    @staticmethod
    def ApplyOperations(request,
                        target,
                        options=(),
                        channel_credentials=None,
                        call_credentials=None,
                        insecure=False,
                        compression=None,
                        wait_for_ready=None,
                        timeout=None,
                        metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sef.handlers.v1.LakeHandler/ApplyOperations',
            sef__handlers__pb2.OperationBatch.SerializeToString,
            sef__handlers__pb2.OperationBatchResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IntrospectEvidence(request,
                           target,
                           options=(),
                           channel_credentials=None,
                           call_credentials=None,
                           insecure=False,
                           compression=None,
                           wait_for_ready=None,
                           timeout=None,
                           metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sef.handlers.v1.LakeHandler/IntrospectEvidence',
            sef__handlers__pb2.EvidenceRequest.SerializeToString,
            sef__handlers__pb2.EvidenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class VaultHandlerStub(object):
    """Vault handler gRPC API

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ApplyOperations = channel.unary_unary(
            '/sef.handlers.v1.VaultHandler/ApplyOperations',
            request_serializer=sef__handlers__pb2.OperationBatch.SerializeToString,
            response_deserializer=sef__handlers__pb2.OperationBatchResult.FromString,
            _registered_method=True)
        self.IntrospectEvidence = channel.unary_unary(
            '/sef.handlers.v1.VaultHandler/IntrospectEvidence',
            request_serializer=sef__handlers__pb2.EvidenceRequest.SerializeToString,
            response_deserializer=sef__handlers__pb2.EvidenceResponse.FromString,
            _registered_method=True)
        self.ProbeLinkCandidates = channel.unary_unary(
            '/sef.handlers.v1.VaultHandler/ProbeLinkCandidates',
            request_serializer=sef__handlers__pb2.LinkProbeRequest.SerializeToString,
            response_deserializer=sef__handlers__pb2.LinkProbeResponse.FromString,
            _registered_method=True)


class VaultHandlerServicer(object):
    """Vault handler gRPC API

    """

    def ApplyOperations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IntrospectEvidence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProbeLinkCandidates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VaultHandlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'ApplyOperations': grpc.unary_unary_rpc_method_handler(
            servicer.ApplyOperations,
            request_deserializer=sef__handlers__pb2.OperationBatch.FromString,
            response_serializer=sef__handlers__pb2.OperationBatchResult.SerializeToString,
        ),
        'IntrospectEvidence': grpc.unary_unary_rpc_method_handler(
            servicer.IntrospectEvidence,
            request_deserializer=sef__handlers__pb2.EvidenceRequest.FromString,
            response_serializer=sef__handlers__pb2.EvidenceResponse.SerializeToString,
        ),
        'ProbeLinkCandidates': grpc.unary_unary_rpc_method_handler(
            servicer.ProbeLinkCandidates,
            request_deserializer=sef__handlers__pb2.LinkProbeRequest.FromString,
            response_serializer=sef__handlers__pb2.LinkProbeResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'sef.handlers.v1.VaultHandler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sef.handlers.v1.VaultHandler', rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class VaultHandler(object):
    """Vault handler gRPC API

    """

    @staticmethod
    def ApplyOperations(request,
                        target,
                        options=(),
                        channel_credentials=None,
                        call_credentials=None,
                        insecure=False,
                        compression=None,
                        wait_for_ready=None,
                        timeout=None,
                        metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sef.handlers.v1.VaultHandler/ApplyOperations',
            sef__handlers__pb2.OperationBatch.SerializeToString,
            sef__handlers__pb2.OperationBatchResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IntrospectEvidence(request,
                           target,
                           options=(),
                           channel_credentials=None,
                           call_credentials=None,
                           insecure=False,
                           compression=None,
                           wait_for_ready=None,
                           timeout=None,
                           metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sef.handlers.v1.VaultHandler/IntrospectEvidence',
            sef__handlers__pb2.EvidenceRequest.SerializeToString,
            sef__handlers__pb2.EvidenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProbeLinkCandidates(request,
                            target,
                            options=(),
                            channel_credentials=None,
                            call_credentials=None,
                            insecure=False,
                            compression=None,
                            wait_for_ready=None,
                            timeout=None,
                            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sef.handlers.v1.VaultHandler/ProbeLinkCandidates',
            sef__handlers__pb2.LinkProbeRequest.SerializeToString,
            sef__handlers__pb2.LinkProbeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
